app:
  name: 'echo-boilerplate'
  version: '1.0.0'
  debug: true

http:
  host: '0.0.0.0'
  port: '5000'

postgres:
  host: '0.0.0.0'
  port: 5432
  user: postgres
  pass: secret
  dbname: dummy

cache:
  driver: redis # redis|memcached

redis:
  host: 0.0.0.0
  port: 6379
  password: 

memcached:
  hosts: 
    - 0.0.0.0:11211
    - 127.0.0.1:11211
    - localhost:11211