CREATE SEQUENCE permissions_seq;

CREATE TABLE permissions
(
	id INT NOT NULL DEFAULT NEXTVAL ('permissions_seq'),
	uuid CHAR(36) NOT NULL UNIQUE,
    parent_id INT NOT NULL DEFAULT 0,
	name VARCHAR(255) UNIQUE NOT NULL,
	type VARCHAR(255) NOT NULL,
	created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INT DEFAULT NULL,
	updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INT DEFAULT NULL,

	PRIMARY KEY (id)
);